### ISSUE TITLE
"ReferenceError: getComputedStyle is not defined" after upgrading to 1.0.0

### ISSUE THREAD

**Issue by kaiyoma** [goldenyz/react-perfect-scrollbar#32]
If I upgrade to 1.0.0 and run my component tests, I get this stack trace:

```
ReferenceError: getComputedStyle is not defined
    at get (...\node_modules\perfect-scrollbar\dist\perfect-scrollbar.common.js:9:3)
    at new PerfectScrollbar (...\node_modules\perfect-scrollbar\dist\perfect-scrollbar.common.js:1131:16)
    at ScrollBar.componentDidMount (...\node_modules\react-perfect-scrollbar\lib\scrollbar.js:63:24)
    at commitLifeCycles (...\node_modules\react-dom\cjs\react-dom.development.js:8770:24)
    at commitAllLifeCycles (...\node_modules\react-dom\cjs\react-dom.development.js:9946:9)
    at Object.invokeGuardedCallback (...\node_modules\react-dom\cjs\react-dom.development.js:491:10)
    at invokeGuardedCallback (...\node_modules\react-dom\cjs\react-dom.development.js:438:27)
    at commitRoot (...\node_modules\react-dom\cjs\react-dom.development.js:10050:9)
    at performWorkOnRoot (...\node_modules\react-dom\cjs\react-dom.development.js:11017:42)
    at performWork (...\node_modules\react-dom\cjs\react-dom.development.js:10967:7)
    at requestWork (...\node_modules\react-dom\cjs\react-dom.development.js:10878:7)
    at scheduleWorkImpl (...\node_modules\react-dom\cjs\react-dom.development.js:10732:11)
    at scheduleWork (...\node_modules\react-dom\cjs\react-dom.development.js:10689:12)
    at scheduleTopLevelUpdate (...\node_modules\react-dom\cjs\react-dom.development.js:11193:5)
    at Object.updateContainer (...\node_modules\react-dom\cjs\react-dom.development.js:11231:7)
    at ...\node_modules\react-dom\cjs\react-dom.development.js:15226:19
    at Object.unbatchedUpdates (...\node_modules\react-dom\cjs\react-dom.development.js:11102:12)
    at renderSubtreeIntoContainer (...\node_modules\react-dom\cjs\react-dom.development.js:15225:17)
    at Object.render (...\node_modules\react-dom\cjs\react-dom.development.js:15290:12)
    at Object.render (...\node_modules\enzyme-adapter-react-16\build\ReactSixteenAdapter.js:218:50)
    at new ReactWrapper (...\node_modules\enzyme\build\ReactWrapper.js:98:16)
    at mount (...\node_modules\enzyme\build\mount.js:19:10)
    at Suite.<anonymous> (C:/Users/Kyle Getz/Work/event-viewer/src/components/DataGrid/__test__/index.spec.js:88:19)
    at Object.create (...\node_modules\mocha\lib\interfaces\common.js:112:19)
    at context.describe.context.context (...\node_modules\mocha\lib\interfaces\bdd.js:44:27)
    at Object.<anonymous> (C:/Users/Kyle Getz/Work/event-viewer/src/components/DataGrid/__test__/index.spec.js:16:1)
    at Module._compile (module.js:635:30)
    at loader (...\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (...\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at ...\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (...\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (...\node_modules\mocha\lib\mocha.js:536:10)
    at Object.<anonymous> (...\node_modules\mocha\bin\_mocha:582:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by goldenyz** [comment]
Have you using [mocha-jsdom](https://www.npmjs.com/package/mocha-jsdom) for running mocha in node?

**Comment by kaiyoma** [comment]
No, we don't use that package. We use `enzyme`, `jsdom`, and `mocha` separately and have a setup script similar to the one here:

https://github.com/airbnb/enzyme/blob/master/docs/guides/jsdom.md

**Comment by goldenyz** [comment]
Fine. I will close the issue, then.
